In [115]:
import pandas as pd
import tabula
import datetime

columns = [
    "Date",
    "Time",
    "Stretcher Pts hrly",
    "Stretcher Pts cum",
    "Ambulatory Pts hrly",
    "Ambulatory Pts cum",
    "Total Inflow hrly",
    "Total Inflow cum",
    "Ambulances hrly",
    "Ambulances cum",
    "FLS hrly",
    "Adm. requests cum",
    "Admissions cum",
    "Pts.waiting for admission CUM",
    "Triage hallway pts TBS",
    "Re-Oriented Nurse cum",
    "Re-Oriented MD QTrack D/C",
    "Re-Oriented MD QTrack NotD/C",
    "Resus Pts",
    "Totalpts in PODs except Psych",
    "Green Pts",
    "Green Pts TBS",
    "Yellow PTS",
    "Yellow Pts TBS",
    "Orancge Pts except psych",
    "Orange Pts TBS",
    "Consults > 2h in PODS except IM",
    "Consult for IM >4h in PODS",
    "Plain films reqs > 2 h in PODs",
    "CTs reqs > 2 h in PODs",
    "Post POD (Family room)",
    "Stretcher Pts in Vertical",
    "Stretcher Pts TBS in Vertical",
    "Stretcher Pts in Vertical on Lazyboy",
    "Vertical Pts Waiting for Results",
    "Ambulatory Pts in Vertical",
    "Ambulatory Pts TBS in Vertical",
    "QTrack Patients TBS",
    "GARAGE patient TBS",
    "Consults > 2h in Vertical Except IM",
    "Consult for IM >4h in Vertical",
    "Plain films reqs > 2 hr in Vertical",
    "CTs reqs > 2 hrs in Vertical",
    "Psych Stretcher Pts1pt",
    "Psych pts waiting for admission",
]

url = "https://www.dropbox.com/s/ckijmipu33z3feg/HourlyReport.pdf?dl=1"

In [116]:
output = []
first_row = tabula.read_pdf(url, pages=1, area=[[200, 6, 206, 1002]], silent=True)[0]
first_row = first_row.columns.tolist()
first_row_dict = dict(zip(columns, first_row))
output.append(first_row_dict)
first_row_date = first_row_dict['Date']
for row_start in [211, 223, 235, 247, 259, 271, 283]:
    try:
        new_row = tabula.read_pdf(url, pages=1, area=[[row_start, 0, row_start+7, 1002]], silent=True)[0]
        new_row = new_row.columns.tolist()
        new_row.insert(0, first_row_date)
        new_row_dict = dict(zip(columns, new_row))
        output.append(new_row_dict)
    except:
        break
output_df = pd.DataFrame(output)
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,FLS hrly,Adm. requests cum,Admissions cum,Pts.waiting for admission CUM,Triage hallway pts TBS,Re-Oriented Nurse cum,Re-Oriented MD QTrack D/C,Re-Oriented MD QTrack NotD/C,Resus Pts,Totalpts in PODs except Psych,Green Pts,Green Pts TBS,Yellow PTS,Yellow Pts TBS,Orancge Pts except psych,Orange Pts TBS,Consults > 2h in PODS except IM,Consult for IM >4h in PODS,Plain films reqs > 2 h in PODs,CTs reqs > 2 h in PODs,Post POD (Family room),Stretcher Pts in Vertical,Stretcher Pts TBS in Vertical,Stretcher Pts in Vertical on Lazyboy,Vertical Pts Waiting for Results,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/17/22,11,11.1,34,2,11.2,13,45,2.1,6,0,13.1,7,14,0.1,2.2,2.3,0.2,2.4,33,13.2,0.3,9,1,11.3,0.4,9.1,1.1,1.2,1.3,0.5,16,2.5,3,5,1.4,1.5,0.6,1.6,0.7,0.8,0.9,0.10,1.7,1.8
1,01/17/22,10,8,23,0,9,8.1,32,0.1,4,0.2,10.1,6,13,0.3,2,0.4,0.5,4.1,32.1,12,0.6,9.1,0.7,11,0.8,12.1,1,0.9,1.1,0.10,12.2,0.11,3,5,0.12,0.13,0.14,3.1,2.1,0.15,0.16,0.17,1.2,1.3
2,01/17/22,9,5,15,5.1,9.1,10,24,2,4,1,7,3,15.1,0,2.1,0.1,0.2,5.2,32,12,1.1,9.2,2.2,11,0.3,12.1,2.3,0.4,1.2,0.5,8,1.3,3.1,3.2,0.6,0.7,0.8,4.1,1.4,0.9,0.10,1.5,2.4,2.5
3,01/17/22,8,6,10,0,4,6.1,14,2,2.1,1,7,2.2,16,0.1,0.2,0.3,0.4,5,29,10.1,0.5,9,0.6,10.2,0.7,10.3,2.3,0.8,1.1,0.9,2.4,0.10,2.5,1.2,4.1,4.2,0.11,2.6,1.3,0.12,0.13,1.4,2.7,2.8
4,01/17/22,7,1,4,2,4.1,3,8,0,0.1,0.2,7.1,2.1,16,0.3,0.4,0.5,0.6,3.1,29,10,0.7,9,0.8,10.1,0.9,10.2,1.1,0.10,0.11,0.12,2.2,0.13,2.3,1.2,2.4,2.5,0.14,1.3,0.15,0.16,0.17,1.4,2.6,2.7
5,01/17/22,6,2,3,0,2.1,2.2,5,0.1,0.2,0.3,6.1,2.3,15,0.4,0.5,0.6,0.7,3.1,30,10,0.8,9,0.9,11,0.10,10.1,1,0.11,1.1,0.12,2.4,0.13,2.5,0.14,1.2,0.15,0.16,0.17,0.18,0.19,0.20,1.3,2.6,2.7
6,01/17/22,5,0,1,0.1,2,0.2,3,0.3,0.4,0.5,5.1,1.1,15,0.6,0.7,0.8,0.9,3.1,29,10,0.10,8,0.11,11,0.12,12,1.2,0.13,0.14,0.15,2.1,0.16,2.2,1.3,0.17,0.18,0.19,0.20,0.21,0.22,0.23,1.4,2.3,2.4
7,01/17/22,4,0,1,0.1,2,0.2,3,0.3,0.4,0.5,4.1,0.6,14,0.7,0.8,0.9,0.10,4.2,29,10,0.11,9,0.12,10.1,0.13,10.2,2.1,0.14,0.15,0.16,2.2,0.17,2.3,0.18,2.4,0.19,0.20,0.21,0.22,0.23,0.24,0.25,2.5,2.6

In [117]:
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,FLS hrly,Adm. requests cum,Admissions cum,Pts.waiting for admission CUM,Triage hallway pts TBS,Re-Oriented Nurse cum,Re-Oriented MD QTrack D/C,Re-Oriented MD QTrack NotD/C,Resus Pts,Totalpts in PODs except Psych,Green Pts,Green Pts TBS,Yellow PTS,Yellow Pts TBS,Orancge Pts except psych,Orange Pts TBS,Consults > 2h in PODS except IM,Consult for IM >4h in PODS,Plain films reqs > 2 h in PODs,CTs reqs > 2 h in PODs,Post POD (Family room),Stretcher Pts in Vertical,Stretcher Pts TBS in Vertical,Stretcher Pts in Vertical on Lazyboy,Vertical Pts Waiting for Results,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/17/22,11,11.1,34,2,11.2,13,45,2.1,6,0,13.1,7,14,0.1,2.2,2.3,0.2,2.4,33,13.2,0.3,9,1,11.3,0.4,9.1,1.1,1.2,1.3,0.5,16,2.5,3,5,1.4,1.5,0.6,1.6,0.7,0.8,0.9,0.10,1.7,1.8
1,01/17/22,10,8,23,0,9,8.1,32,0.1,4,0.2,10.1,6,13,0.3,2,0.4,0.5,4.1,32.1,12,0.6,9.1,0.7,11,0.8,12.1,1,0.9,1.1,0.10,12.2,0.11,3,5,0.12,0.13,0.14,3.1,2.1,0.15,0.16,0.17,1.2,1.3
2,01/17/22,9,5,15,5.1,9.1,10,24,2,4,1,7,3,15.1,0,2.1,0.1,0.2,5.2,32,12,1.1,9.2,2.2,11,0.3,12.1,2.3,0.4,1.2,0.5,8,1.3,3.1,3.2,0.6,0.7,0.8,4.1,1.4,0.9,0.10,1.5,2.4,2.5
3,01/17/22,8,6,10,0,4,6.1,14,2,2.1,1,7,2.2,16,0.1,0.2,0.3,0.4,5,29,10.1,0.5,9,0.6,10.2,0.7,10.3,2.3,0.8,1.1,0.9,2.4,0.10,2.5,1.2,4.1,4.2,0.11,2.6,1.3,0.12,0.13,1.4,2.7,2.8
4,01/17/22,7,1,4,2,4.1,3,8,0,0.1,0.2,7.1,2.1,16,0.3,0.4,0.5,0.6,3.1,29,10,0.7,9,0.8,10.1,0.9,10.2,1.1,0.10,0.11,0.12,2.2,0.13,2.3,1.2,2.4,2.5,0.14,1.3,0.15,0.16,0.17,1.4,2.6,2.7
5,01/17/22,6,2,3,0,2.1,2.2,5,0.1,0.2,0.3,6.1,2.3,15,0.4,0.5,0.6,0.7,3.1,30,10,0.8,9,0.9,11,0.10,10.1,1,0.11,1.1,0.12,2.4,0.13,2.5,0.14,1.2,0.15,0.16,0.17,0.18,0.19,0.20,1.3,2.6,2.7
6,01/17/22,5,0,1,0.1,2,0.2,3,0.3,0.4,0.5,5.1,1.1,15,0.6,0.7,0.8,0.9,3.1,29,10,0.10,8,0.11,11,0.12,12,1.2,0.13,0.14,0.15,2.1,0.16,2.2,1.3,0.17,0.18,0.19,0.20,0.21,0.22,0.23,1.4,2.3,2.4
7,01/17/22,4,0,1,0.1,2,0.2,3,0.3,0.4,0.5,4.1,0.6,14,0.7,0.8,0.9,0.10,4.2,29,10,0.11,9,0.12,10.1,0.13,10.2,2.1,0.14,0.15,0.16,2.2,0.17,2.3,0.18,2.4,0.19,0.20,0.21,0.22,0.23,0.24,0.25,2.5,2.6

In [118]:
output_df["Green Pts TBS"]

0     0.3
1     0.6
2     1.1
3     0.5
4     0.7
5     0.8
6    0.10
7    0.11
Name: Green Pts TBS, dtype: object

In [119]:
missing_columns = []
first_row = tabula.read_pdf(url, pages=1, area=[[200, 308, 215, 341]], silent=True)[0]
first_row = first_row.columns.tolist()
first_row_dict = dict(zip(['Total Stretcher pts', 'Triage hallway pts'], first_row))
missing_columns.append(first_row_dict)
for row_start in [212, 224, 236, 248, 260, 272, 284]:
    try:
        new_row = tabula.read_pdf(url, pages=1, area=[[row_start, 308, row_start+8, 341]], silent=True)[0]
        new_row = new_row.columns.tolist()
        new_row_dict = dict(zip(['Total Stretcher pts', 'Triage hallway pts'], new_row))
        missing_columns.append(new_row_dict)
    except:
        break
missing_columns_df = pd.DataFrame(missing_columns)
missing_columns_df

  Total Stretcher pts Triage hallway pts
0                  52                  0
1                  49                  0
2                  47                  0
3                  38                  0
4                  36                  0
5                  37                  0
6                  36                  0
7                  37                  0

In [88]:
output_df = pd.concat([output_df, missing_columns_df], axis=1)
output_df = output_df.dropna()
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,Total Stretcher pts,Triage hallway pts
0,01/17/22,10,8,27,0,5,8.1,32,0.1,4,...,0.14,3.1,2.1,0.15,0.16,0.17,1.2,1.3,49,0
1,01/17/22,9,8,19,2,5,10,24,2.1,4,...,0.8,4.1,1.4,0.9,0.10,1.5,2.5,2.6,47,0
2,01/17/22,8,6,11,0,3,6.1,14,2,2.1,...,0.11,2.6,1.3,0.12,0.13,1.4,2.7,2.8,38,0
3,01/17/22,7,1,5,2,3,3.1,8,0,0.1,...,0.14,1.3,0.15,0.16,0.17,1.4,2.6,2.7,36,0
4,01/17/22,6,2,4,0,1,2.1,5,0.1,0.2,...,0.16,0.17,0.18,0.19,0.20,1.4,2.5,2.6,37,0
5,01/17/22,5,0,2,0.1,1,0.2,3,0.3,0.4,...,0.19,0.20,0.21,0.22,0.23,1.4,2.3,2.4,36,0
6,01/17/22,4,0,2,0.1,1,0.2,3,0.3,0.4,...,0.20,0.21,0.22,0.23,0.24,0.25,2.5,2.6,37,0
7,01/17/22,3,2,2.1,1,1.1,3.1,3.2,0,0.1,...,1.5,0.14,0.15,1.6,0.16,0.17,2.6,2.7,40,0

In [89]:
newColumns = [
    "Date",
    "Time",
    "Stretcher Pts hrly",
    "Stretcher Pts cum",
    "Ambulatory Pts hrly",
    "Ambulatory Pts cum",
    "Total Inflow hrly",
    "Total Inflow cum",
    "Ambulances hrly",
    "Ambulances cum",
    "FLS hrly",
    "Adm. requests cum",
    "Admissions cum",
    "Pts.waiting for admission CUM",
    "Total Stretcher pts",
    "Triage hallway pts",
    "Triage hallway pts TBS",
    "Re-Oriented Nurse cum",
    "Re-Oriented MD QTrack D/C",
    "Re-Oriented MD QTrack NotD/C",
    "Resus Pts",
    "Totalpts in PODs except Psych",
    "Green Pts",
    "Green Pts TBS",
    "Yellow PTS",
    "Yellow Pts TBS",
    "Orancge Pts except psych",
    "Orange Pts TBS",
    "Consults > 2h in PODS except IM",
    "Consult for IM >4h in PODS",
    "Plain films reqs > 2 h in PODs",
    "CTs reqs > 2 h in PODs",
    "Post POD (Family room)",
    "Stretcher Pts in Vertical",
    "Stretcher Pts TBS in Vertical",
    "Stretcher Pts in Vertical on Lazyboy",
    "Vertical Pts Waiting for Results",
    "Ambulatory Pts in Vertical",
    "Ambulatory Pts TBS in Vertical",
    "QTrack Patients TBS",
    "GARAGE patient TBS",
    "Consults > 2h in Vertical Except IM",
    "Consult for IM >4h in Vertical",
    "Plain films reqs > 2 hr in Vertical",
    "CTs reqs > 2 hrs in Vertical",
    "Psych Stretcher Pts1pt",
    "Psych pts waiting for admission",
]
output_df = output_df[newColumns]
for column in output_df.columns.tolist():
    if column in ['Date']:
        continue
    output_df[column] = output_df[column].astype('float').astype('int')
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/17/22,10,8,27,0,5,8,32,0,4,...,0,0,0,3,2,0,0,0,1,1
1,01/17/22,9,8,19,2,5,10,24,2,4,...,0,0,0,4,1,0,0,1,2,2
2,01/17/22,8,6,11,0,3,6,14,2,2,...,4,4,0,2,1,0,0,1,2,2
3,01/17/22,7,1,5,2,3,3,8,0,0,...,2,2,0,1,0,0,0,1,2,2
4,01/17/22,6,2,4,0,1,2,5,0,0,...,1,0,0,0,0,0,0,1,2,2
5,01/17/22,5,0,2,0,1,0,3,0,0,...,0,0,0,0,0,0,0,1,2,2
6,01/17/22,4,0,2,0,1,0,3,0,0,...,2,0,0,0,0,0,0,0,2,2
7,01/17/22,3,2,2,1,1,3,3,0,0,...,2,2,1,0,0,1,0,0,2,2

In [90]:
pd.set_option('display.max_columns', None)
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,FLS hrly,Adm. requests cum,Admissions cum,Pts.waiting for admission CUM,Total Stretcher pts,Triage hallway pts,Triage hallway pts TBS,Re-Oriented Nurse cum,Re-Oriented MD QTrack D/C,Re-Oriented MD QTrack NotD/C,Resus Pts,Totalpts in PODs except Psych,Green Pts,Green Pts TBS,Yellow PTS,Yellow Pts TBS,Orancge Pts except psych,Orange Pts TBS,Consults > 2h in PODS except IM,Consult for IM >4h in PODS,Plain films reqs > 2 h in PODs,CTs reqs > 2 h in PODs,Post POD (Family room),Stretcher Pts in Vertical,Stretcher Pts TBS in Vertical,Stretcher Pts in Vertical on Lazyboy,Vertical Pts Waiting for Results,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/17/22,10,8,27,0,5,8,32,0,4,0,10,6,13,49,0,0,2,0,0,4,32,12,0,9,0,11,0,12,1,0,1,0,12,0,3,5,0,0,0,3,2,0,0,0,1,1
1,01/17/22,9,8,19,2,5,10,24,2,4,1,7,3,15,47,0,0,2,0,0,5,32,12,1,9,2,11,0,12,2,0,1,0,8,1,3,3,0,0,0,4,1,0,0,1,2,2
2,01/17/22,8,6,11,0,3,6,14,2,2,1,7,2,16,38,0,0,0,0,0,5,29,10,0,9,0,10,0,10,2,0,1,0,2,0,2,1,4,4,0,2,1,0,0,1,2,2
3,01/17/22,7,1,5,2,3,3,8,0,0,0,7,2,16,36,0,0,0,0,0,3,29,10,0,9,0,10,0,10,1,0,0,0,2,0,2,1,2,2,0,1,0,0,0,1,2,2
4,01/17/22,6,2,4,0,1,2,5,0,0,0,6,2,15,37,0,0,0,0,0,3,30,10,0,9,0,11,0,10,1,0,1,0,2,0,2,0,1,0,0,0,0,0,0,1,2,2
5,01/17/22,5,0,2,0,1,0,3,0,0,0,5,1,15,36,0,0,0,0,0,3,29,10,0,8,0,11,0,12,1,0,0,0,2,0,2,1,0,0,0,0,0,0,0,1,2,2
6,01/17/22,4,0,2,0,1,0,3,0,0,0,4,0,14,37,0,0,0,0,0,4,29,10,0,9,0,10,0,10,2,0,0,0,2,0,2,0,2,0,0,0,0,0,0,0,2,2
7,01/17/22,3,2,2,1,1,3,3,0,0,0,3,0,13,40,0,0,0,0,1,4,32,10,0,11,0,11,0,9,1,1,0,0,2,0,2,0,2,2,1,0,0,1,0,0,2,2

In [95]:
output_df["ds"] = pd.to_datetime(
    output_df["Date"] + " " + (output_df["Time"] - 1).astype(str) + ":00") + datetime.timedelta(hours=1)
output_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,FLS hrly,Adm. requests cum,Admissions cum,Pts.waiting for admission CUM,Total Stretcher pts,Triage hallway pts,Triage hallway pts TBS,Re-Oriented Nurse cum,Re-Oriented MD QTrack D/C,Re-Oriented MD QTrack NotD/C,Resus Pts,Totalpts in PODs except Psych,Green Pts,Green Pts TBS,Yellow PTS,Yellow Pts TBS,Orancge Pts except psych,Orange Pts TBS,Consults > 2h in PODS except IM,Consult for IM >4h in PODS,Plain films reqs > 2 h in PODs,CTs reqs > 2 h in PODs,Post POD (Family room),Stretcher Pts in Vertical,Stretcher Pts TBS in Vertical,Stretcher Pts in Vertical on Lazyboy,Vertical Pts Waiting for Results,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,Total Pod TBS,ds
0,01/17/22,10,8,27,0,5,8,32,0,4,0,10,6,13,49,0,0,2,0,0,4,32,12,0,9,0,11,0,12,1,0,1,0,12,0,3,5,0,0,0,3,2,0,0,0,1,1,0,2022-01-17 10:00:00
1,01/17/22,9,8,19,2,5,10,24,2,4,1,7,3,15,47,0,0,2,0,0,5,32,12,1,9,2,11,0,12,2,0,1,0,8,1,3,3,0,0,0,4,1,0,0,1,2,2,3,2022-01-17 09:00:00
2,01/17/22,8,6,11,0,3,6,14,2,2,1,7,2,16,38,0,0,0,0,0,5,29,10,0,9,0,10,0,10,2,0,1,0,2,0,2,1,4,4,0,2,1,0,0,1,2,2,0,2022-01-17 08:00:00
3,01/17/22,7,1,5,2,3,3,8,0,0,0,7,2,16,36,0,0,0,0,0,3,29,10,0,9,0,10,0,10,1,0,0,0,2,0,2,1,2,2,0,1,0,0,0,1,2,2,0,2022-01-17 07:00:00
4,01/17/22,6,2,4,0,1,2,5,0,0,0,6,2,15,37,0,0,0,0,0,3,30,10,0,9,0,11,0,10,1,0,1,0,2,0,2,0,1,0,0,0,0,0,0,1,2,2,0,2022-01-17 06:00:00
5,01/17/22,5,0,2,0,1,0,3,0,0,0,5,1,15,36,0,0,0,0,0,3,29,10,0,8,0,11,0,12,1,0,0,0,2,0,2,1,0,0,0,0,0,0,0,1,2,2,0,2022-01-17 05:00:00
6,01/17/22,4,0,2,0,1,0,3,0,0,0,4,0,14,37,0,0,0,0,0,4,29,10,0,9,0,10,0,10,2,0,0,0,2,0,2,0,2,0,0,0,0,0,0,0,2,2,0,2022-01-17 04:00:00
7,01/17/22,3,2,2,1,1,3,3,0,0,0,3,0,13,40,0,0,0,0,1,4,32,10,0,11,0,11,0,9,1,1,0,0,2,0,2,0,2,2,1,0,0,1,0,0,2,2,0,2022-01-17 03:00:00

In [96]:

output_df['Total Pod TBS'] = output_df['Green Pts TBS']+output_df['Yellow Pts TBS']+output_df['Orange Pts TBS']
output_df['Total Pod TBS']

0    0
1    3
2    0
3    0
4    0
5    0
6    0
7    0
Name: Total Pod TBS, dtype: int64

In [97]:
output_df['Total Vertical TBS'] = output_df['Stretcher Pts TBS in Vertical']+output_df['Ambulatory Pts TBS in Vertical']+output_df['QTrack Patients TBS']+output_df['GARAGE patient TBS']
output_df['Total Vertical TBS']

0    3
1    5
2    6
3    3
4    0
5    0
6    0
7    3
Name: Total Vertical TBS, dtype: int64

In [111]:

current_df = pd.read_csv("../data/current.csv")

recent_df = pd.read_csv("../data/recent.csv")
recent_df.ds = pd.to_datetime(recent_df.ds)

since2020_df = pd.read_csv("../data/since-2020.csv")
since2020_df.ds = pd.to_datetime(since2020_df.ds)


print(len(recent_df))
print(len(since2020_df))


recent_df = pd.concat([recent_df, output_df], ignore_index=True)

since2020_df = pd.concat([since2020_df, output_df], ignore_index=True)

print(len(recent_df))
print(len(since2020_df))

recent_df = recent_df.drop_duplicates(subset='ds',keep="last").sort_values(by=['ds'], ascending=False)
since2020_df = since2020_df.drop_duplicates(subset='ds',keep="last").sort_values(by=['ds'], ascending=False)



print(len(recent_df))
print(len(since2020_df))


recent_df.to_csv("../data/recent.csv", index=False)
since2020_df.to_csv("../data/since-2020.csv", index=False)

390
17923
398
17931
390
17921

In [109]:
recent_df['Total Pod TBS'] = recent_df['Green Pts TBS']+recent_df['Yellow Pts TBS']+recent_df['Orange Pts TBS']
recent_df['Total Vertical TBS'] = recent_df['Stretcher Pts TBS in Vertical']+recent_df['Ambulatory Pts TBS in Vertical']+recent_df['QTrack Patients TBS']+recent_df['GARAGE patient TBS']
recent_df.to_csv("../data/recent.csv", index=False)

In [110]:
recent_df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,FLS hrly,Adm. requests cum,Admissions cum,Pts.waiting for admission CUM,Total Stretcher pts,Triage hallway pts,Triage hallway pts TBS,Re-Oriented Nurse cum,Re-Oriented MD QTrack D/C,Re-Oriented MD QTrack NotD/C,Resus Pts,Totalpts in PODs except Psych,Green Pts,Green Pts TBS,Yellow PTS,Yellow Pts TBS,Orancge Pts except psych,Orange Pts TBS,Consults > 2h in PODS except IM,Consult for IM >4h in PODS,Plain films reqs > 2 h in PODs,CTs reqs > 2 h in PODs,Post POD (Family room),Stretcher Pts in Vertical,Stretcher Pts TBS in Vertical,Stretcher Pts in Vertical on Lazyboy,Vertical Pts Waiting for Results,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds,Total Pod TBS,Total Vertical TBS
390,01/17/22,10,8,27,0,5,8,32,0,4,0,10,6,13,49,0,0,2,0,0,4,32,12,0,9,0,11,0,12,1,0,1,0,12,0,3,5,0,0,0,3,2,0,0,0,1,1,2022-01-17 10:00:00,0,3
391,01/17/22,9,8,19,2,5,10,24,2,4,1,7,3,15,47,0,0,2,0,0,5,32,12,1,9,2,11,0,12,2,0,1,0,8,1,3,3,0,0,0,4,1,0,0,1,2,2,2022-01-17 09:00:00,3,5
392,01/17/22,8,6,11,0,3,6,14,2,2,1,7,2,16,38,0,0,0,0,0,5,29,10,0,9,0,10,0,10,2,0,1,0,2,0,2,1,4,4,0,2,1,0,0,1,2,2,2022-01-17 08:00:00,0,6
393,01/17/22,7,1,5,2,3,3,8,0,0,0,7,2,16,36,0,0,0,0,0,3,29,10,0,9,0,10,0,10,1,0,0,0,2,0,2,1,2,2,0,1,0,0,0,1,2,2,2022-01-17 07:00:00,0,3
394,01/17/22,6,2,4,0,1,2,5,0,0,0,6,2,15,37,0,0,0,0,0,3,30,10,0,9,0,11,0,10,1,0,1,0,2,0,2,0,1,0,0,0,0,0,0,1,2,2,2022-01-17 06:00:00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,01/01/22,5,3,9,0,7,3,16,1,5,0,3,1,12,42,0,0,0,0,0,3,34,11,0,12,0,11,0,16,0,0,1,0,2,0,1,0,2,1,0,2,0,0,4,2,3,3,2022-01-01 05:00:00,0,3
386,01/01/22,4,1,6,2,7,3,13,0,4,0,3,1,12,45,0,0,0,0,0,4,35,12,0,14,0,9,0,10,1,2,2,0,3,0,1,1,1,1,0,1,0,0,0,2,3,3,2022-01-01 04:00:00,0,2
387,01/01/22,3,2,5,1,5,3,10,1,4,0,3,1,12,45,0,0,0,0,0,5,34,13,0,12,0,9,0,8,1,2,2,0,3,1,1,1,0,0,0,0,0,0,0,2,3,3,2022-01-01 03:00:00,0,1
388,01/01/22,2,2,3,1,4,3,7,1,3,0,3,1,12,42,0,0,0,0,0,3,34,13,0,11,0,10,0,6,0,3,3,0,2,0,0,0,1,1,0,5,0,0,0,2,3,3,2022-01-01 02:00:00,0,6
389,01/01/22,1,1,1,3,3,4,4,2,2,0,2,1,11,44,0,0,0,0,0,3,36,15,1,11,0,10,1,5,1,2,3,0,2,0,2,0,1,1,0,3,0,0,0,2,3,3,2022-01-01 01:00:00,2,4

In [ ]:
since2020_df = pd.read_csv("data/since-2020.csv")

df8 = (
    pd.concat([archive, df6], ignore_index=True)
    .sort_values(by=["Date", "Time"], ascending=False)
    .drop_duplicates(keep="first")
)

df8.to_csv("data/since-2020.csv", index=False)

In [ ]:
# Clean up datetimes

df9 = pd.read_csv("data/recent.csv")

hours_added = datetime.timedelta(hours=1)

df9["ds"] = pd.to_datetime(
    df9["Date"] + " " + (df9["Time"] - 1).astype(str) + ":00") + datetime.timedelta(hours=1)

df9.to_csv("data/recent-clean.csv", index=False)