In [5]:
import pandas as pd
import datetime

In [8]:
df = pd.read_csv('../data/recent.csv')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/11/22,21,4,106,1,56,5,162,0,30,...,2,0,0,1,0,0,1,3,7,5
1,01/11/22,20,5,101,1,56,6,157,0,30,...,8,2,0,5,1,0,0,1,7,4
2,01/11/22,19,10,94,5,57,15,151,1,30,...,7,3,0,3,2,0,0,0,7,4
3,01/11/22,18,10,87,4,49,14,136,4,28,...,5,1,0,1,4,0,0,0,7,4
4,01/11/22,17,4,76,5,46,9,122,2,24,...,8,2,0,0,6,1,0,0,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,01/01/22,5,3,9,0,7,3,16,1,5,...,2,1,0,2,0,0,4,2,3,3
257,01/01/22,4,1,6,2,7,3,13,0,4,...,1,1,0,1,0,0,0,2,3,3
258,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,0,0,2,3,3
259,01/01/22,2,2,3,1,4,3,7,1,3,...,1,1,0,5,0,0,0,2,3,3
260,01/01/22,1,1,1,3,3,4,4,2,2,...,1,1,0,3,0,0,0,2,3,3

In [10]:
# hours_added = datetime.timedelta(hours = 1)
df['ds'] = pd.to_datetime(df['Date'] + ' ' + (df['Time'] - 1).astype(str) + ':00') + datetime.timedelta(hours = 1)
df.head(24)

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds
0,01/11/22,21,4,106,1,56,5,162,0,30,...,0,0,1,0,0,1,3,7,5,2022-01-11 21:00:00
1,01/11/22,20,5,101,1,56,6,157,0,30,...,2,0,5,1,0,0,1,7,4,2022-01-11 20:00:00
2,01/11/22,19,10,94,5,57,15,151,1,30,...,3,0,3,2,0,0,0,7,4,2022-01-11 19:00:00
3,01/11/22,18,10,87,4,49,14,136,4,28,...,1,0,1,4,0,0,0,7,4,2022-01-11 18:00:00
4,01/11/22,17,4,76,5,46,9,122,2,24,...,2,0,0,6,1,0,0,7,4,2022-01-11 17:00:00
5,01/11/22,16,5,72,5,41,10,113,1,22,...,2,0,0,3,1,0,4,10,6,2022-01-11 16:00:00
6,01/11/22,15,7,67,4,36,11,103,2,21,...,3,0,1,5,0,0,5,11,7,2022-01-11 15:00:00
7,01/11/22,14,5,59,2,33,7,92,1,19,...,1,0,1,4,0,0,3,10,7,2022-01-11 14:00:00
8,01/11/22,13,5,54,5,31,10,85,2,18,...,4,0,1,4,0,0,0,9,6,2022-01-11 13:00:00
9,01/11/22,12,7,50,4,25,11,75,2,16,...,5,0,0,4,0,1,3,10,6,2022-01-11 12:00:00
10,01/11/22,11,10,46,3,18,13,64,2,14,...,4,0,2,7,0,0,2,11,6,2022-01-11 11:00:00
11,01/11/22,10,10,37,4,14,14,51,3,12,...,7,0,0,6,0,0,0,11,6,2022-01-11 10:00:00
12,01/11/22,9,5,25,5,12,10,37,3,9,...,1,0,6,4,0,0,0,11,6,2022-01-11 09:00:00
13,01/11/22,8,3,20,2,6,5,26,0,6,...,5,0,2,4,0,0,0,12,7,2022-01-11 08:00:00
14,01/11/22,7,2,16,1,5,3,21,0,6,...,1,0,1,3,0,0,0,12,7,2022-01-11 07:00:00
15,01/11/22,6,1,14,1,4,2,18,0,6,...,0,0,1,2,0,0,0,12,7,2022-01-11 06:00:00
16,01/11/22,5,0,13,0,3,0,16,0,6,...,1,0,0,2,0,0,0,11,7,2022-01-11 05:00:00
17,01/11/22,4,2,13,0,3,2,16,0,6,...,1,0,0,3,0,0,0,11,7,2022-01-11 04:00:00
18,01/11/22,3,5,11,2,3,7,14,3,6,...,1,0,0,4,0,0,0,10,7,2022-01-11 03:00:00
19,01/11/22,2,1,6,0,1,1,7,1,3,...,5,0,0,4,0,0,1,10,7,2022-01-11 02:00:00
20,01/11/22,1,6,6,0,0,6,6,2,2,...,6,0,3,4,0,1,0,9,5,2022-01-11 01:00:00
21,01/10/22,24,3,143,2,82,5,225,3,40,...,5,0,3,5,0,0,1,9,5,2022-01-11 00:00:00
22,01/10/22,23,6,146,0,74,6,220,0,37,...,4,0,7,4,0,0,1,9,4,2022-01-10 23:00:00
23,01/10/22,22,4,143,1,71,5,214,3,37,...,8,0,7,4,0,0,3,11,4,2022-01-10 22:00:00

In [7]:
hours_added = datetime.timedelta(hours = 1)

df['ds2'] = df['ds'] + hours_added

df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds,ds2
0,01/11/22,21,4,106,1,56,5,162,0,30,...,0,1,0,0,1,3,7,5,2022-01-11 20:00:00,2022-01-11 21:00:00
1,01/11/22,20,5,101,1,56,6,157,0,30,...,0,5,1,0,0,1,7,4,2022-01-11 19:00:00,2022-01-11 20:00:00
2,01/11/22,19,10,94,5,57,15,151,1,30,...,0,3,2,0,0,0,7,4,2022-01-11 18:00:00,2022-01-11 19:00:00
3,01/11/22,18,10,87,4,49,14,136,4,28,...,0,1,4,0,0,0,7,4,2022-01-11 17:00:00,2022-01-11 18:00:00
4,01/11/22,17,4,76,5,46,9,122,2,24,...,0,0,6,1,0,0,7,4,2022-01-11 16:00:00,2022-01-11 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,01/01/22,5,3,9,0,7,3,16,1,5,...,0,2,0,0,4,2,3,3,2022-01-01 04:00:00,2022-01-01 05:00:00
257,01/01/22,4,1,6,2,7,3,13,0,4,...,0,1,0,0,0,2,3,3,2022-01-01 03:00:00,2022-01-01 04:00:00
258,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,2,3,3,2022-01-01 02:00:00,2022-01-01 03:00:00
259,01/01/22,2,2,3,1,4,3,7,1,3,...,0,5,0,0,0,2,3,3,2022-01-01 01:00:00,2022-01-01 02:00:00
260,01/01/22,1,1,1,3,3,4,4,2,2,...,0,3,0,0,0,2,3,3,2022-01-01 00:00:00,2022-01-01 01:00:00