In [1]:
import pandas as pd

In [24]:
df = pd.read_csv('../data/recent.csv')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/09/22,22,3,96,3,50,6,146,3,31,...,2,0,0,1,0,0,0,0,7,2
1,01/09/22,21,7,95,2,45,9,140,1,28,...,4,1,0,3,0,0,0,0,6,2
2,01/09/22,20,6,89,3,42,9,131,1,27,...,6,4,0,2,1,0,0,1,6,3
3,01/09/22,19,6,81,3,40,9,121,3,25,...,5,4,0,2,2,0,0,1,6,3
4,01/09/22,18,6,75,5,37,11,112,2,22,...,1,1,1,3,4,0,0,0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,01/01/22,5,3,9,0,7,3,16,1,5,...,2,1,0,2,0,0,4,2,3,3
210,01/01/22,4,1,6,2,7,3,13,0,4,...,1,1,0,1,0,0,0,2,3,3
211,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,0,0,2,3,3
212,01/01/22,2,2,3,1,4,3,7,1,3,...,1,1,0,5,0,0,0,2,3,3
213,01/01/22,1,1,1,3,3,4,4,2,2,...,1,1,0,3,0,0,0,2,3,3

In [25]:
df['ds'] = pd.to_datetime(df['Date'] + ' ' + (df['Time'] - 1).astype(str) + ':00')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds
0,01/09/22,22,3,96,3,50,6,146,3,31,...,0,0,1,0,0,0,0,7,2,2022-01-09 21:00:00
1,01/09/22,21,7,95,2,45,9,140,1,28,...,1,0,3,0,0,0,0,6,2,2022-01-09 20:00:00
2,01/09/22,20,6,89,3,42,9,131,1,27,...,4,0,2,1,0,0,1,6,3,2022-01-09 19:00:00
3,01/09/22,19,6,81,3,40,9,121,3,25,...,4,0,2,2,0,0,1,6,3,2022-01-09 18:00:00
4,01/09/22,18,6,75,5,37,11,112,2,22,...,1,1,3,4,0,0,0,6,3,2022-01-09 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,01/01/22,5,3,9,0,7,3,16,1,5,...,1,0,2,0,0,4,2,3,3,2022-01-01 04:00:00
210,01/01/22,4,1,6,2,7,3,13,0,4,...,1,0,1,0,0,0,2,3,3,2022-01-01 03:00:00
211,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,0,2,3,3,2022-01-01 02:00:00
212,01/01/22,2,2,3,1,4,3,7,1,3,...,1,0,5,0,0,0,2,3,3,2022-01-01 01:00:00
213,01/01/22,1,1,1,3,3,4,4,2,2,...,1,0,3,0,0,0,2,3,3,2022-01-01 00:00:00