In [5]:
import pandas as pd
import datetime

In [2]:
df = pd.read_csv('../data/recent.csv')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts in Vertical,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission
0,01/11/22,21,4,106,1,56,5,162,0,30,...,2,0,0,1,0,0,1,3,7,5
1,01/11/22,20,5,101,1,56,6,157,0,30,...,8,2,0,5,1,0,0,1,7,4
2,01/11/22,19,10,94,5,57,15,151,1,30,...,7,3,0,3,2,0,0,0,7,4
3,01/11/22,18,10,87,4,49,14,136,4,28,...,5,1,0,1,4,0,0,0,7,4
4,01/11/22,17,4,76,5,46,9,122,2,24,...,8,2,0,0,6,1,0,0,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,01/01/22,5,3,9,0,7,3,16,1,5,...,2,1,0,2,0,0,4,2,3,3
257,01/01/22,4,1,6,2,7,3,13,0,4,...,1,1,0,1,0,0,0,2,3,3
258,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,0,0,2,3,3
259,01/01/22,2,2,3,1,4,3,7,1,3,...,1,1,0,5,0,0,0,2,3,3
260,01/01/22,1,1,1,3,3,4,4,2,2,...,1,1,0,3,0,0,0,2,3,3

In [3]:
df['ds'] = pd.to_datetime(df['Date'] + ' ' + (df['Time'] - 1).astype(str) + ':00')
df

,Date,Time,Stretcher Pts hrly,Stretcher Pts cum,Ambulatory Pts hrly,Ambulatory Pts cum,Total Inflow hrly,Total Inflow cum,Ambulances hrly,Ambulances cum,...,Ambulatory Pts TBS in Vertical,QTrack Patients TBS,GARAGE patient TBS,Consults > 2h in Vertical Except IM,Consult for IM >4h in Vertical,Plain films reqs > 2 hr in Vertical,CTs reqs > 2 hrs in Vertical,Psych Stretcher Pts1pt,Psych pts waiting for admission,ds
0,01/11/22,21,4,106,1,56,5,162,0,30,...,0,0,1,0,0,1,3,7,5,2022-01-11 20:00:00
1,01/11/22,20,5,101,1,56,6,157,0,30,...,2,0,5,1,0,0,1,7,4,2022-01-11 19:00:00
2,01/11/22,19,10,94,5,57,15,151,1,30,...,3,0,3,2,0,0,0,7,4,2022-01-11 18:00:00
3,01/11/22,18,10,87,4,49,14,136,4,28,...,1,0,1,4,0,0,0,7,4,2022-01-11 17:00:00
4,01/11/22,17,4,76,5,46,9,122,2,24,...,2,0,0,6,1,0,0,7,4,2022-01-11 16:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,01/01/22,5,3,9,0,7,3,16,1,5,...,1,0,2,0,0,4,2,3,3,2022-01-01 04:00:00
257,01/01/22,4,1,6,2,7,3,13,0,4,...,1,0,1,0,0,0,2,3,3,2022-01-01 03:00:00
258,01/01/22,3,2,5,1,5,3,10,1,4,...,0,0,0,0,0,0,2,3,3,2022-01-01 02:00:00
259,01/01/22,2,2,3,1,4,3,7,1,3,...,1,0,5,0,0,0,2,3,3,2022-01-01 01:00:00
260,01/01/22,1,1,1,3,3,4,4,2,2,...,1,0,3,0,0,0,2,3,3,2022-01-01 00:00:00

In [6]:
hours_added = datetime.timedelta(hours = 1)

df['ds2'] = df['ds'] + hours_added

df

NameError: name 'ds' is not defined