In [8]:
from datetime import date
import pandas as pd

old_weather = pd.read_csv('../data/archiveAndForecast.csv')
old_weather.datetime = pd.to_datetime(old_weather.datetime)
old_weather

,datetime,temp,dew,humidity,precip,windspeed,sealevelpressure
0,2020-01-01 00:00:00,0.3,-1.6,87.00,0.0,12.0,99.30
1,2020-01-01 01:00:00,0.2,-1.8,86.00,0.0,12.0,99.29
2,2020-01-01 02:00:00,0.1,-1.5,89.00,0.0,13.0,99.30
3,2020-01-01 03:00:00,-0.2,-1.1,93.00,0.0,12.0,99.30
4,2020-01-01 04:00:00,-0.5,-1.5,93.00,0.0,15.0,99.28
...,...,...,...,...,...,...,...
21453,2022-06-13 19:00:00,20.7,10.5,52.01,0.0,15.8,1013.00
21454,2022-06-13 20:00:00,18.9,11.6,62.56,0.0,15.5,1013.00
21455,2022-06-13 21:00:00,17.8,12.4,70.66,0.0,11.2,1013.00
21456,2022-06-13 22:00:00,16.5,13.1,80.32,0.0,9.4,1013.00
21457,2022-06-13 23:00:00,15.8,13.3,85.09,0.0,10.8,1013.00

In [5]:
forecast = pd.read_csv('https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/montreal/next24hours?unitGroup=metric&include=hours&key=NDD4FLZ37NRPKGD82DRZWXGHU&contentType=csv')
forecast.datetime = pd.to_datetime(forecast.datetime)
forecast.head()

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"Montréal, QC, Canada",2022-06-12 00:00:00,18.7,18.7,9.9,56.30,0.0,0.0,NaN,0,...,1011.1,0,25.3,0,NaN,0,3,Clear,clear-night,"CWVQ,CWIZ,CWTA"
1,"Montréal, QC, Canada",2022-06-12 01:00:00,17.6,17.6,10.3,61.95,0.0,0.0,NaN,0,...,1011.2,26,20.5,0,NaN,0,3,Partially cloudy,partly-cloudy-night,"CWVQ,CWIZ,CWTA"
2,"Montréal, QC, Canada",2022-06-12 02:00:00,16.4,16.4,9.5,63.36,0.0,0.0,NaN,0,...,1011.3,3,19.0,0,NaN,0,3,Clear,clear-night,"CWVQ,CWIZ,CWTA"
3,"Montréal, QC, Canada",2022-06-12 03:00:00,16.8,16.8,10.7,66.93,0.0,0.0,NaN,0,...,1011.5,2,22.7,0,NaN,0,10,Clear,clear-night,"CWVQ,CWIZ,CWTA"
4,"Montréal, QC, Canada",2022-06-12 04:00:00,15.4,15.4,10.8,73.64,0.0,0.0,NaN,0,...,1011.6,0,17.7,0,NaN,0,10,Clear,clear-night,"CWVQ,CWIZ,CWTA"

In [14]:
archiveAndForecast = pd.concat([old_weather, forecast], join='inner').drop_duplicates(subset='datetime',keep='last')
archiveAndForecast

,datetime,temp,dew,humidity,precip,windspeed,sealevelpressure
0,2020-01-01 00:00:00,0.3,-1.6,87.00,0.0,12.0,99.30
1,2020-01-01 01:00:00,0.2,-1.8,86.00,0.0,12.0,99.29
2,2020-01-01 02:00:00,0.1,-1.5,89.00,0.0,13.0,99.30
3,2020-01-01 03:00:00,-0.2,-1.1,93.00,0.0,12.0,99.30
4,2020-01-01 04:00:00,-0.5,-1.5,93.00,0.0,15.0,99.28
...,...,...,...,...,...,...,...
43,2022-06-13 19:00:00,20.7,10.5,52.01,0.0,15.8,1013.00
44,2022-06-13 20:00:00,18.9,11.6,62.56,0.0,15.5,1013.00
45,2022-06-13 21:00:00,17.8,12.4,70.66,0.0,11.2,1013.00
46,2022-06-13 22:00:00,16.5,13.1,80.32,0.0,9.4,1013.00
47,2022-06-13 23:00:00,15.8,13.3,85.09,0.0,10.8,1013.00

In [17]:
old_weather = pd.read_csv('../data/archiveAndForecast.csv')
old_weather.ds = pd.to_datetime(old_weather.ds)

forecast = pd.read_csv('https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/montreal/next24hours?unitGroup=metric&include=hours&key=NDD4FLZ37NRPKGD82DRZWXGHU&contentType=csv')
forecast.ds = pd.to_datetime(forecast.datetime)

archiveAndForecast = pd.concat([old_weather, forecast], join='inner').drop_duplicates(subset='ds', keep='last')

archiveAndForecast

/tmp/ipykernel_2021/3894326466.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  forecast.ds = pd.to_datetime(forecast.datetime)

KeyError: Index(['ds'], dtype='object')

In [33]:
old_weather = pd.read_csv('../data/weatherArchiveAndForecast.csv')
old_weather.ds = pd.to_datetime(old_weather.ds)

In [26]:
forecast = pd.read_csv('https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/montreal/next24hours?unitGroup=metric&include=hours&key=NDD4FLZ37NRPKGD82DRZWXGHU&contentType=csv')
forecast = forecast.rename(columns={'datetime':'ds'})
forecast.ds = pd.to_datetime(forecast.ds)

In [28]:
archiveAndForecast = pd.concat([old_weather, forecast], join='inner').drop_duplicates(subset='ds', keep='last')

In [32]:
archiveAndForecast.to_csv('../data/weatherArchiveAndForecast.csv', index=False)

In [34]:
old_weather

,ds,temp,dew,humidity,precip,windspeed,sealevelpressure
0,2020-01-01 00:00:00,0.3,-1.6,87.00,0.0,12.0,99.30
1,2020-01-01 01:00:00,0.2,-1.8,86.00,0.0,12.0,99.29
2,2020-01-01 02:00:00,0.1,-1.5,89.00,0.0,13.0,99.30
3,2020-01-01 03:00:00,-0.2,-1.1,93.00,0.0,12.0,99.30
4,2020-01-01 04:00:00,-0.5,-1.5,93.00,0.0,15.0,99.28
...,...,...,...,...,...,...,...
21453,2022-06-13 19:00:00,20.7,10.5,52.01,0.0,15.8,1013.00
21454,2022-06-13 20:00:00,18.9,11.6,62.56,0.0,15.5,1013.00
21455,2022-06-13 21:00:00,17.8,12.4,70.66,0.0,11.2,1013.00
21456,2022-06-13 22:00:00,16.5,13.1,80.32,0.0,9.4,1013.00
21457,2022-06-13 23:00:00,15.8,13.3,85.09,0.0,10.8,1013.00